name: Package ndcurves
on:
  repository_dispatch:
    types:
    - package-master
  push:
    branches:
    - debian
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      main-branch: debian
      update-stable-and-head: true
      matrix: |
          {
            "dist": ["bionic", "focal", "jammy"],
            "arch": ["amd64"],
            "include":
            [
              {"dist": "bionic", "arch": "i386" }
            ]
          }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
